project:
  type: website

website:
  title: ""
  search: false
  navbar:
    background: dark

    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - data_code.qmd
      - CV.qmd
  page-footer:
    left: "Copyright 2025, Xolani Sibande"
    right:
      - icon: github
        href: https://github.com/xolaniss
      - icon: linkedin
        href: https://www.linkedin.com/in/xolanisibande
      - icon: envelope
        href: mailto:xolaniss@gmail.com
    background: light
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
filters:
  - fontawesome

editor: source

